name: Achraf Garai
email: achrafgarai@hotmail.com 
links: 
  - title: Behance
    url: https://www.behance.net/achrafgarai 

  - title: Instagram
    url:  https://www.instagram.com/achraf_garai/

  - title: LinkedIn
    url:  https://www.linkedin.com/in/achraf-garai/
    
  - title: Blog 
    url: https://www.achrafgarai.com
